name: CI
on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Check for requirements.txt
        run: |
          if [ ! -f requirement.txt ]; then
            echo "ERROR: requirements.txt not found in repository root."
            exit 1
          fi
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unittests
        run: |
          python -m pytest -q

  deploy-pages:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Copy docs to public
        run: |
          mkdir public
          cp -r docs/* public/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
